### ISSUE TITLE
Map wait button causes location icons to remain on screen

### ISSUE THREAD

**Issue by 01010100010100100100100101000111** [DRincs-Productions/NQTR-toolkit#40]
If you open the map, press the wait button, the location icons remain on screen after the map closes, clicking the map then clears them (but does not open the map, requiring two click to get it back open)

**Comment by BlackRam-oss** [comment]
> If you open the map, press the wait button, the location icons remain on screen after the map closes, clicking the map then clears them (but does not open the map, requiring two click to get it back open)

I thank you for the report I fixed it.
