### ISSUE TITLE
Can't close screen in certain circumstances

### ISSUE THREAD

**Issue by 01010100010100100100100101000111** [DRincs-Productions/NQTR-toolkit#43]
1) Open the memo screen 

2) Click Backpack, Smartphone or Map icon while memo screen is open, then close it 

3) Now can't click the close button on the memo screen 

Might be easiest to not allow click-through when screen is open if that's possible? will do a PR if I figure it out before you take a look

**Comment by BlackRam-oss** [comment]
@01010100010100100100100101000111  if you want I invited you into the project so you can make changes directly by looking for a new branch

**Comment by 01010100010100100100100101000111** [comment]
Accepted it, thank you, going to take some time getting up to speed though, hope to be of some use soon!
